export default function Head() {
  return (
    <>
      <title>MDiary</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create todo app" />
      <link rel="icon" href="/MDiary_Logo.svg" />
    </>
  );
}