'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import Headers from '../components/Headerlans'
import SupabaseProvider from '../components/providers/supabase-provider'
import supabase from '../utils/supabase/supabase-client'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <SupabaseProvider session={supabase}>

          <ThemeProvider attribute='class'>
            <Headers></Headers>
            {children}
          </ThemeProvider>
          </SupabaseProvider>
        </body>
    </html>
  )
}
